# Generated by Django 5.1 on 2025-06-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_smart', '0002_remove_dadosensor_ambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
